"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
console_title_template = "{{ .Shell }} in {{ .Folder }}"
final_space = true
version = 2

[[blocks]]
alignment = "left"
type = "prompt"

  [[blocks.segments]]
  background = "blue"
  foreground = "#ffffff"
  powerline_symbol = ""
  style = "powerline"
  template = "   {{ .Path }} "
  type = "path"

    [blocks.segments.properties]
    style = "full"

  [[blocks.segments]]
  background = "#fffb38"
  background_templates = [
  "{{ if or (.Working.Changed) (.Staging.Changed) }}#FF9248{{ end }}",
  "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#ff4500{{ end }}",
  "{{ if gt .Ahead 0 }}#B388FF{{ end }}",
  "{{ if gt .Behind 0 }}#B388FF{{ end }}"
]
  foreground = "#193549"
  powerline_symbol = ""
  style = "powerline"
  template = " {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} "
  type = "git"

    [blocks.segments.properties]
    fetch_stash_count = true
    fetch_status = true
    fetch_upstream_icon = true

  [[blocks.segments]]
  background = "#ebcc34"
  foreground = "#000000"
  powerline_symbol = ""
  # style = "diamond"
  style = "powerline"
  template = "  {{.Cluster}}@{{if .Namespace}}{{.Namespace}} {{end}} "
  type = "kubectl"

  [[blocks.segments]]
  background = "#2e9599"
  background_templates = [ "{{ if gt .Code 0 }}#f1184c{{ end }}" ]
  foreground = "#ffffff"
  leading_diamond = "<transparent,background></>"
  style = "diamond"
  template = "  {{ if gt .Code 0 }} {{ reason .Code }}{{ else }}{{ end }} "
  trailing_diamond = ""
  type = "status"

    [blocks.segments.properties]
    always_enabled = true

[[blocks]]
alignment = "right"
type = "prompt"


  [[blocks.segments]]
  background = "#2e9599"
  foreground = "#111111"
  invert_powerline = true
  leading_diamond = ""
  style = "diamond"
  template = "  {{ .CurrentDate | date .Format }} "
  trailing_diamond = ""
  type = "time"


[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      "{{if gt .Code 0}}red{{end}}",
      "{{if eq .Code 0}}magenta{{end}}",
    ]
    background = 'transparent'
    template = '❯'

[transient_prompt]
  foreground_templates = [
    "{{if gt .Code 0}}red{{end}}",
    "{{if eq .Code 0}}magenta{{end}}",
  ]
  background = 'transparent'
  template = '❯ '

[secondary_prompt]
  foreground = 'magenta'
  background = 'transparent'
  template = '❯❯ '
