# ./.config/terminator/config

[global_config]
  enabled_plugins = LaunchpadCodeURLHandler, APTURLHandler
[keybindings]
  zoom_in = <Alt>plus
  zoom_out = <Alt>minus
  new_tab = <Alt>t
  go_up = <Alt>k
  go_down = <Alt>j
  go_left = <Alt>h
  go_right = <Alt>l
  split_horiz = <Shift><Alt>o
  split_vert = <Shift><Alt>e
  toggle_zoom = <Shift><Alt>m
  next_tab = <Alt>Right
  prev_tab = <Alt>Left
  layout_launcher = ""
[profiles]
  [[default]]
    background_darkness = 0.13
    font = Mononoki Nerd Font Mono Bold 14
    scrollback_lines = 10000
    use_system_font = False
    cursor_color = "#f2d5cf"
    background_color = "#303446"
    foreground_color = "#c6d0f5"
    palette = "#51576d:#e78284:#a6d189:#e5c890:#8caaee:#f4b8e4:#81c8be:#b5bfe2:#626880:#e78284:#a6d189:#e5c890:#8caaee:#f4b8e4:#81c8be:#a5adce"
    background_image = None
  [[Catppuccin_Latte]]
    cursor_color = "#dc8a78"
    background_color = "#eff1f5"
    foreground_color = "#4c4f69"
    palette = "#5c5f77:#d20f39:#40a02b:#df8e1d:#1e66f5:#ea76cb:#179299:#acb0be:#6c6f85:#d20f39:#40a02b:#df8e1d:#1e66f5:#ea76cb:#179299:#bcc0cc"
    background_image = None
  [[Catppuccin_Frappe]]
    background_color = "#303446"
    foreground_color = "#c6d0f5"
    palette = "#51576d:#e78284:#a6d189:#e5c890:#8caaee:#f4b8e4:#81c8be:#b5bfe2:#626880:#e78284:#a6d189:#e5c890:#8caaee:#f4b8e4:#81c8be:#a5adce"
    background_image = None
  [[Catppuccin_Macchiato]]
    cursor_color = "#f4dbd6"
    background_color = "#24273a"
    foreground_color = "#cad3f5"
    palette = "#494d64:#ed8796:#a6da95:#eed49f:#8aadf4:#f5bde6:#8bd5ca:#b8c0e0:#5b6078:#ed8796:#a6da95:#eed49f:#8aadf4:#f5bde6:#8bd5ca:#a5adcb"
    background_image = None
  [[Catppuccin_Mocha]]
    cursor_color = "#f5e0dc"
    background_color = "#1e1e2e"
    foreground_color = "#cdd6f4"
    palette = "#45475a:#f38ba8:#a6e3a1:#f9e2af:#89b4fa:#f5c2e7:#94e2d5:#bac2de:#585b70:#f38ba8:#a6e3a1:#f9e2af:#89b4fa:#f5c2e7:#94e2d5:#a6adc8"
    background_image = None
[layouts]
  [[default]]
    [[[window0]]]
      type = Window
      parent = ""
    [[[child1]]]
      type = Terminal
      parent = window0
[plugins]
